### ISSUE TITLE
PluginInfo.Location isn't set

### ISSUE THREAD

**Issue by exp111** [BepInEx/BepInEx.Debug#11]
On loaded plugins the Location isn't set.
Could this be added?

**Comment by ManlyMarco** [comment]
Are you referring to ScriptEngine?

**Comment by exp111** [comment]
Yeah sorry should've specified that.

Also a screenshot using UnityExplorer
![grafik](https://user-images.githubusercontent.com/17885980/213493836-a3f7b74e-75e7-42dd-ba48-f5131da16fff.png)

**Comment by ManlyMarco** [comment]
What do you need this for? The Location is null because the assembly is loaded from memory since it needs to be modified on the fly https://github.com/BepInEx/BepInEx.Debug/blob/master/src/ScriptEngine/ScriptEngine.cs#L76-L83
The dll file itself is not actually used outside of this code.

**Comment by exp111** [comment]
I'm writing a plugin that needs to access the folder the dll is in, which i usually access through that location field. Currently bypassed it by hardcoding, but that seems meh. Why not set the location to the path of the assembly?

**Comment by Windows10CE** [comment]
They're talking about PluginInfo.Location, not Assembly.Location

**Comment by ManlyMarco** [comment]
> They're talking about PluginInfo.Location, not Assembly.Location

It's the same thing <https://github.com/BepInEx/BepInEx/blob/6aabdb5ff9500fca541dbd66df7fbd7fe1dacd78/Runtimes/Unity/BepInEx.Unity.Mono/BaseUnityPlugin.cs#L30>

I guess it has a private setter so it can be set through reflection by ScriptEngine, though that seems like something that's going to break sooner or later.

**Comment by ManlyMarco** [comment]
Fixed in 2772448447d033a47ef695913a538e96e59a79da
