### ISSUE TITLE
ScriptEngine + Unity Asset Bundles

### ISSUE THREAD

**Issue by BlackPhoenix134** [BepInEx/BepInEx.Debug#5]
Hey,

I am using Asset Bundles. When attaching a script to a prefab it saves the assembly + script name to reference it again when loading the prefab.
However, this breaks with ScriptEngine because the Assemblies get renamed to [AssemblyName]-[someNumber].

Is there any possibility that this can be changed to support reloading of Asset Bundles?

**Comment by ManlyMarco** [comment]
This can't be fixed without major changes in how the plugin works, therefore it's a nofix.
