### ISSUE TITLE
ScriptEngine: NetworkingAPI is not loaded.

### ISSUE THREAD

**Issue by peterbozso** [BepInEx/BepInEx.Debug#9]
I have my mod set up like this: https://github.com/peterbozso/ror2arena/blob/2aaee329ed68f7394f3f4acbc00fe9c4afa6ad95/src/Arena/ArenaPlugin.cs#L12

When I try to load it with ScriptEngine, I get this error:
```text
[Error: Unity Log] InvalidOperationException: NetworkingAPI is not loaded. Please use [R2APISubmoduleDependency(nameof(NetworkingAPI)]
Stack trace:
R2API.Networking.NetworkingAPI.RegisterMessageType[TMessage] () (at <26362b8786344089806e7c616760b8c5>:0)
Arena.ArenaPlugin.Init () (at <f70a40f7dc5e49f7937380b2b1d5b23d>:0)
Arena.ArenaPlugin.Awake () (at <f70a40f7dc5e49f7937380b2b1d5b23d>:0)
UnityEngine.GameObject:AddComponent(Type)
ScriptEngine.<>c__DisplayClass16_2:<LoadDLL>b__1()
ScriptEngine.<DelayAction>d__18:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```

Loading my mod normally, without ScriptEngine, I don't get this error. Before adding the dependency on NetworkingAPI, ScriptEngine was able to load my mod without issues as well.

**Comment by Windows10CE** [comment]
This is due to how R2API checks for dependencies. To fix it, run the game with the environment variable `R2API_DEBUG` set to `true`, which will enable all submodules. It's not really something that can be handled on the ScriptEngine side
